# Generated by Django 6.0.3 on 2026-05-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_gallery_options_alter_photo_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
